### ISSUE TITLE
suggestion: /bu for custom tags

### ISSUE THREAD

**Issue by Thunder33345** [FlamingGenius/MessageSystem#1]
bu = broadcast user
instate of only having /bgod /bhero /bcia
user can use custom name /bu <name>
btw the php tags in the readme.md is broken
or allow user to create shortcut if you thing sometimes /bu <name> is too long
using /bus (shortcut) <shortcut name>
allow user to edit it on config

**Comment by CoderJoeW** [comment]
Im not entirely sure what your saying can you please provide a more clear explanation please

**Comment by Thunder33345** [comment]
fair enough that time i am rushing
so i mean /bu <name> <message>
/bus <shortcut name> <massage>
(edit shortcut in config)
does this helps?

**Comment by CoderJoeW** [comment]
So you want to set custom cmd names for all commands in the config

**Comment by CoderJoeW** [comment]
I added code to the project where you could change the command from lets say the command is /bcia you can change the command to /cia not sure if this is what you meant if not let me know and i will change it
